### PR TITLE
TravisCI working

### PR DESCRIPTION
**Pull request by mrsimonemms**
This is a weird one.

The content of the file hasn't changed between commits [febca65](https://github.com/dylanparry/ceylon/commit/febca65575bdb6cca06525f1a8f4da66cf38b27b) and [1747b33](https://github.com/dylanparry/ceylon/commit/1747b33a920b351aabe46071a68d6ec3cea12d99). Indeed, the current file is a literal copy and paste from the first commit.

It is physically a different file so I have to assume that there's some meta data that is causing Travis is ignoring some of it. It is picking it up, but I have no idea why it wasn't working previously.

``` yml
language: node_js
node_js:
- "node"
matrix:
  fast_finish: true
sudo: false
```

### CODE REVIEW

**Comment by mrsimonemms** [comment]
Would recommend adding additional versions of NodeJS to ensure full compatibility across versions. These are what I tend to use:

``` yml
language: node_js
node_js:
- "node"
- "5.11"
- "4.4"
- "iojs"
- "0.12"
- "0.10"
matrix:
  fast_finish: true
sudo: false
```

**Comment by dylanparry** [comment]
Thanks. That appears to have fixed it :) I’ll probably add a few extra versions of node, maybe back to v4 as it uses a few ES6 features that aren't compatible with the older versions. Next step is for me to figure out why the Travis build is only running 7 unit tests when there are 41 running on my laptop.

**Comment by mrsimonemms** [comment]
That's an easy one.

Globbing on npm scripts doesn't really work.  If you have a file structure...
- src
  - dir1
    - file1.js
    - file2.js
  - dir2
    - file3.js
  - dir3
    - dir4
      - file4.js

And run your tests with the glob `src/**/*.js`, because there is only one `**` it will only pick up the first level of directories (ie, ignoring `dir4`).

To fix, you need to change your mocha command to `mocha src/**/*.js src/**/**/*.js`.

It's very annoying, but that's the reason and a fix (there's probably a globbing npm script that will do it for you but I tend not to add that in as it's extra dependencies).

---

If you had your tests in a tests directory rather than in spec files (ie, in `/test/unit`), you could also do `mocha --recursive test/unit`

**Comment by dylanparry** [comment]
Thanks. On another note, I added some other Node versions to my config, and now the same problem is back again. I'm guessing that my text editor is doing something strange—I wonder if it's the line endings?

**Comment by dylanparry** [comment]
Seems to be an issue with Windows. No idea what is the real cause, but editing the file directly on GihHub seems to have fixed it. Will have to remember not to touch it ever again! Thanks again for all your help.

**Comment by mrsimonemms** [comment]
It's probably line endings then. Have a look at [EditorConfig](http://editorconfig.org). That will allow you to specify how the IDE behaves.

This will be a good start for you. You'll may need to install a plugin if you use VSCode.

```
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true
quote_type = 'double'
```

**Pull request merged**
